export const db = "main-stack-xpert"
export const questionsCollection = "questions"
export const answersCollection = "answers"
export const commentsCollection = "comments"
export const votesCollection = "votes"
export const questionsAttachmentBucket = "questions-attachments"